# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
---
version: 2

submodules:
  include:
    - docs/sphinx-resources

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - libapt-pkg-dev
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    install:
      - uv sync --frozen --group docs --group dev-noble
    build:
      html:
        - uv run sphinx-build -T -b dirhtml docs $READTHEDOCS_OUTPUT/html
    post_checkout:
      - git fetch --tags --unshallow # Also fetch tags
      - git describe # Make sure we get a proper version

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
